### ISSUE TITLE
Add IPFS hosted images support if the preview mode is enabled

### ISSUE THREAD

**Issue by ghost** [twisterarmy/twister-html#24]
![2021-07-06_23-54](https://user-images.githubusercontent.com/76843085/124665599-94184f00-deb5-11eb-975d-d97d0a71c313.png)

**Comment by d47081** [comment]
At this moment IPFS is absolutely not useful and expensive by hardware resources 
If somebody ready to implement this feature - feel free to send PR or reopen the ticket.
