### ISSUE TITLE
[blaster] rollback pull/26 to the official state if not be merged

### ISSUE THREAD

**Issue by ghost** [twisterarmy/twister-html#27]
Before make new updates (to safe the official contributing compatibility, README.md)
https://github.com/twisterarmy/twister-html/pull/26

**Comment by d47081** [comment]
Currently, we are maintain 3 separated branches - master/blaster and TA edition, there is no goal to keep the compatibility between these branches. Pretty possible we'll stop to make the PR as no reaction there and takes a time of that.

Contribution Details:
https://github.com/twisterarmy/twister-html#contribute
